# Archivo de configuración para Render
services:
  # Servicio para el Backend (API, Servidor)
  - type: web
    name: dobble-backend
    env: node # Especifica el entorno, en este caso Node.js
    plan: free # Puedes cambiar al plan que necesites
    rootDir: ./backend # Le dice a Render que trabaje dentro de la carpeta 'backend'
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars: # Aquí defines tus variables de entorno
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL # Ejemplo si usas una base de datos de Render
        fromDatabase:
          name: dobble-database # Debes crear una base de datos en Render con este nombre
          property: connectionString

  # Servicio para el Frontend (Sitio Estático)
  - type: static
    name: dobble-frontend
    plan: free
    rootDir: ./frontend # Le dice a Render que trabaje dentro de la carpeta 'frontend'
    buildCommand: "npm install && npm run build"
    publishDir: build # La carpeta que se genera después del 'build'. Podría ser 'dist' en tu caso.
